sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dantedxwolf/imagetest -f ./client/Dockerfile.dev ./client

# script:
  - docker run -e CI=true dantedxwolf/imagetest npm run test

after_success:
  #loggin into dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker login --username="piyal.quantum789@gmail.com" --password="4773b502-cc40-415b-bfa4-932c1032242f" registry.heroku.com

script:
  - docker build -t dantedxwolf/reactmulticlient ./client
  - docker tag dantedxwolf/reactmulticlient registry.heroku.com/ancient-scrubland-27709/web 
  - docker build -t dantedxwolf/reactmultiserver ./server
  - docker tag dantedxwolf/reactmultiserver registry.heroku.com/ancient-scrubland-27709/web 
  - docker build -t dantedxwolf/reactmultinginx ./nginx
  - docker tag dantedxwolf/reactmultinginx registry.heroku.com/ancient-scrubland-27709/web 

deploy:
  provider: script
  script:
    docker push dantedxwolf/reactmulticlient;
    docker push dantedxwolf/reactmultiserver;
    docker push dantedxwolf/reactmultinginx;
    docker push registry.heroku.com/ancient-scrubland-27709/web;
    heroku container:release web --app "ancient-scrubland-27709"
  on:
    branch: master


  #pushing images to dockerhub
  # - docker push dantedxwolf/reactmulticlient
  # - docker push dantedxwolf/reactmultiserver
  # - docker push dantedxwolf/reactmultinginx
