sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t imagetest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imagetest npm run test

after_success:
  - docker build -t reactmulticlient ./client
  - docker build -t reactmultiserver ./server
  - docker build -t reactmultinginx ./nginx

  #loggin into dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #pushing images to dockerhub
  - docker push reactmulticlient
  - docker push reactmultinginx
  - docker push reactmultiserver