sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dantedxwolf/imagetest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dantedxwolf/imagetest npm run test

after_success:
  - docker build -t dantedxwolf/reactmulticlient ./client
  - docker build -t dantedxwolf/reactmultiserver ./server
  - docker build -t dantedxwolf/reactmultinginx ./nginx

  #loggin into dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  #pushing images to dockerhub
  - docker push dantedxwolf/reactmulticlient
  - docker push dantedxwolf/reactmultiserver
  - docker push dantedxwolf/reactmultinginx

  deploy:
    provider: heroku
    api_key: "084800ef-3f47-4b90-a86b-3fa3e5d8818f"
    app: "ancient-scrubland-27709"
    ###